version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/oliver006/go-ups-tracking

    steps:
      - checkout
      - run: go get github.com/mattn/goveralls

      - run:
          name: Run tests
          environment:
            DUMMY: "empty"
          command: |
            go test -v -covermode=atomic -cover -race -coverprofile=/tmp/cover.out

      - run:
          name: Upload coverage
          environment:
            DUMMY: "empty"
          command: |
            if [ -n "$COVERALLS_TOKEN" ]; then goveralls -coverprofile=/tmp/cover.out -service=circle-ci -repotoken=$COVERALLS_TOKEN ;  fi
